services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    env_file:
      - /data/secret.env #Portainer data folder
    environment:
      - TZ=Asia/Kolkata
      - RCLONE_RC_USER=${RCLONE_USER}
      - RCLONE_RC_PASS=${RCLONE_PASS}
      #- PUID=1000
      #- PGID=1000
    volumes:
      - /volume1/docker/rclone/config:/config/rclone
      - /volume1/docker/rclone/data:/data
    #ports:
      #- 5572:5572
    restart: unless-stopped
    command: rcd --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :5572 --rc-serve
    networks:
      - internal

networks:
  internal:
    external: true
